/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WholesaleSunglassesRouteImport } from './routes/wholesale-sunglasses'
import { Route as WholesaleRouteImport } from './routes/wholesale'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivateLabelSunglassesRouteImport } from './routes/private-label-sunglasses'
import { Route as OemSunglassesManufacturerRouteImport } from './routes/oem-sunglasses-manufacturer'
import { Route as OemRouteImport } from './routes/oem'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as FounderRouteImport } from './routes/founder'
import { Route as CustomizationRouteImport } from './routes/customization'
import { Route as CustomSunglassesManufacturerRouteImport } from './routes/custom-sunglasses-manufacturer'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductCodeRouteImport } from './routes/product.$code'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const WholesaleSunglassesRoute = WholesaleSunglassesRouteImport.update({
  id: '/wholesale-sunglasses',
  path: '/wholesale-sunglasses',
  getParentRoute: () => rootRouteImport,
} as any)
const WholesaleRoute = WholesaleRouteImport.update({
  id: '/wholesale',
  path: '/wholesale',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateLabelSunglassesRoute = PrivateLabelSunglassesRouteImport.update({
  id: '/private-label-sunglasses',
  path: '/private-label-sunglasses',
  getParentRoute: () => rootRouteImport,
} as any)
const OemSunglassesManufacturerRoute =
  OemSunglassesManufacturerRouteImport.update({
    id: '/oem-sunglasses-manufacturer',
    path: '/oem-sunglasses-manufacturer',
    getParentRoute: () => rootRouteImport,
  } as any)
const OemRoute = OemRouteImport.update({
  id: '/oem',
  path: '/oem',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderRoute = FounderRouteImport.update({
  id: '/founder',
  path: '/founder',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomizationRoute = CustomizationRouteImport.update({
  id: '/customization',
  path: '/customization',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomSunglassesManufacturerRoute =
  CustomSunglassesManufacturerRouteImport.update({
    id: '/custom-sunglasses-manufacturer',
    path: '/custom-sunglasses-manufacturer',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductCodeRoute = ProductCodeRouteImport.update({
  id: '/product/$code',
  path: '/product/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/collection': typeof CollectionRoute
  '/contact': typeof ContactRoute
  '/custom-sunglasses-manufacturer': typeof CustomSunglassesManufacturerRoute
  '/customization': typeof CustomizationRoute
  '/founder': typeof FounderRoute
  '/industries': typeof IndustriesRoute
  '/oem': typeof OemRoute
  '/oem-sunglasses-manufacturer': typeof OemSunglassesManufacturerRoute
  '/private-label-sunglasses': typeof PrivateLabelSunglassesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wholesale': typeof WholesaleRoute
  '/wholesale-sunglasses': typeof WholesaleSunglassesRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$code': typeof ProductCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/collection': typeof CollectionRoute
  '/contact': typeof ContactRoute
  '/custom-sunglasses-manufacturer': typeof CustomSunglassesManufacturerRoute
  '/customization': typeof CustomizationRoute
  '/founder': typeof FounderRoute
  '/industries': typeof IndustriesRoute
  '/oem': typeof OemRoute
  '/oem-sunglasses-manufacturer': typeof OemSunglassesManufacturerRoute
  '/private-label-sunglasses': typeof PrivateLabelSunglassesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wholesale': typeof WholesaleRoute
  '/wholesale-sunglasses': typeof WholesaleSunglassesRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$code': typeof ProductCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/collection': typeof CollectionRoute
  '/contact': typeof ContactRoute
  '/custom-sunglasses-manufacturer': typeof CustomSunglassesManufacturerRoute
  '/customization': typeof CustomizationRoute
  '/founder': typeof FounderRoute
  '/industries': typeof IndustriesRoute
  '/oem': typeof OemRoute
  '/oem-sunglasses-manufacturer': typeof OemSunglassesManufacturerRoute
  '/private-label-sunglasses': typeof PrivateLabelSunglassesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wholesale': typeof WholesaleRoute
  '/wholesale-sunglasses': typeof WholesaleSunglassesRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$code': typeof ProductCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/collection'
    | '/contact'
    | '/custom-sunglasses-manufacturer'
    | '/customization'
    | '/founder'
    | '/industries'
    | '/oem'
    | '/oem-sunglasses-manufacturer'
    | '/private-label-sunglasses'
    | '/sitemap.xml'
    | '/wholesale'
    | '/wholesale-sunglasses'
    | '/admin'
    | '/blog/$slug'
    | '/category/$slug'
    | '/product/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/collection'
    | '/contact'
    | '/custom-sunglasses-manufacturer'
    | '/customization'
    | '/founder'
    | '/industries'
    | '/oem'
    | '/oem-sunglasses-manufacturer'
    | '/private-label-sunglasses'
    | '/sitemap.xml'
    | '/wholesale'
    | '/wholesale-sunglasses'
    | '/admin'
    | '/blog/$slug'
    | '/category/$slug'
    | '/product/$code'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/blog'
    | '/collection'
    | '/contact'
    | '/custom-sunglasses-manufacturer'
    | '/customization'
    | '/founder'
    | '/industries'
    | '/oem'
    | '/oem-sunglasses-manufacturer'
    | '/private-label-sunglasses'
    | '/sitemap.xml'
    | '/wholesale'
    | '/wholesale-sunglasses'
    | '/_authenticated/admin'
    | '/blog/$slug'
    | '/category/$slug'
    | '/product/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  CollectionRoute: typeof CollectionRoute
  ContactRoute: typeof ContactRoute
  CustomSunglassesManufacturerRoute: typeof CustomSunglassesManufacturerRoute
  CustomizationRoute: typeof CustomizationRoute
  FounderRoute: typeof FounderRoute
  IndustriesRoute: typeof IndustriesRoute
  OemRoute: typeof OemRoute
  OemSunglassesManufacturerRoute: typeof OemSunglassesManufacturerRoute
  PrivateLabelSunglassesRoute: typeof PrivateLabelSunglassesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WholesaleRoute: typeof WholesaleRoute
  WholesaleSunglassesRoute: typeof WholesaleSunglassesRoute
  CategorySlugRoute: typeof CategorySlugRoute
  ProductCodeRoute: typeof ProductCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wholesale-sunglasses': {
      id: '/wholesale-sunglasses'
      path: '/wholesale-sunglasses'
      fullPath: '/wholesale-sunglasses'
      preLoaderRoute: typeof WholesaleSunglassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wholesale': {
      id: '/wholesale'
      path: '/wholesale'
      fullPath: '/wholesale'
      preLoaderRoute: typeof WholesaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private-label-sunglasses': {
      id: '/private-label-sunglasses'
      path: '/private-label-sunglasses'
      fullPath: '/private-label-sunglasses'
      preLoaderRoute: typeof PrivateLabelSunglassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oem-sunglasses-manufacturer': {
      id: '/oem-sunglasses-manufacturer'
      path: '/oem-sunglasses-manufacturer'
      fullPath: '/oem-sunglasses-manufacturer'
      preLoaderRoute: typeof OemSunglassesManufacturerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oem': {
      id: '/oem'
      path: '/oem'
      fullPath: '/oem'
      preLoaderRoute: typeof OemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder': {
      id: '/founder'
      path: '/founder'
      fullPath: '/founder'
      preLoaderRoute: typeof FounderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customization': {
      id: '/customization'
      path: '/customization'
      fullPath: '/customization'
      preLoaderRoute: typeof CustomizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-sunglasses-manufacturer': {
      id: '/custom-sunglasses-manufacturer'
      path: '/custom-sunglasses-manufacturer'
      fullPath: '/custom-sunglasses-manufacturer'
      preLoaderRoute: typeof CustomSunglassesManufacturerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$code': {
      id: '/product/$code'
      path: '/product/$code'
      fullPath: '/product/$code'
      preLoaderRoute: typeof ProductCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  CollectionRoute: CollectionRoute,
  ContactRoute: ContactRoute,
  CustomSunglassesManufacturerRoute: CustomSunglassesManufacturerRoute,
  CustomizationRoute: CustomizationRoute,
  FounderRoute: FounderRoute,
  IndustriesRoute: IndustriesRoute,
  OemRoute: OemRoute,
  OemSunglassesManufacturerRoute: OemSunglassesManufacturerRoute,
  PrivateLabelSunglassesRoute: PrivateLabelSunglassesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WholesaleRoute: WholesaleRoute,
  WholesaleSunglassesRoute: WholesaleSunglassesRoute,
  CategorySlugRoute: CategorySlugRoute,
  ProductCodeRoute: ProductCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
